import { ObjectId } from 'mongodb'
import { Chat, Title, User } from '../db.js'

export const adminDeleteUser = async (req, res) => {
  try {
    const objectID = req.body.objectID

    // WE NEED TO DELETE THE TITLE THAT GENERATED BY THAT USER AND ALSO THE HISTORY ABOUT IT
    // EXTRACT THE username FROM THE USERS COLLECTION
    const findUser = await User.findOne({ _id: new ObjectId(objectID) })
    const username = findUser.username

    // FIND ALL THE TITLE GENERATED BY THAT USER
    // EXTRACT THE objectID FROM THE TITLE COLLECTION
    const titleDocuments = await Title.find({ username: username }).toArray()
    const titleObjectIDs = titleDocuments.map((title) => title._id)

    // DELETE DOCUMENTS IN THE "CHAT" COLLECTION WHERE OBJECT ID MATCHES
    await Chat.deleteMany({ titleID: { $in: titleObjectIDs } })

    // DELETE ALL THE TITLE ALSO FROM THE TITLE COLLECTION
    await Title.deleteMany({ username: username })

    // DELETE DOCUMENTS IN THE "USERS" COLLECTION WHERE OBJECT ID MATCHES
    await User.deleteOne({ _id: new ObjectId(objectID) })

    // SUCCESS RESPONSE
    res.status(200).json({ message: 'User deleted' })
  } catch (error) {
    console.error(error)
    res.status(500).json({ error: 'Internal Server Error' })
  }
}